paths:
  /stores/{storeId}/missions:
    post:
      tags:
        - Store
      summary: 가게에 미션 추가하기
      parameters:
        - in: path
          name: storeId
          required: true
          schema:
            type: integer
          description: 가게 ID
          example: 123
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                missionId:
                  type: integer
                  description: 미션 ID
                  example: 789
                missionName:
                  type: string
                  description: 미션 이름
                  example: "특별한 할인 쿠폰 획득"
                description:
                  type: string
                  description: 미션 설명
                  example: "특별한 할인 쿠폰을 획득하세요!"
      responses:
        "200":
          description: 미션 추가 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: "Mission added successfully"
                  data:
                    type: object
                    properties:
                      missionId:
                        type: integer
                        description: 추가된 미션 ID
                        example: 789
                      storeId:
                        type: integer
                        description: 가게 ID
                        example: 123
                      missionName:
                        type: string
                        description: 미션 이름
                        example: "특별한 할인 쿠폰 획득"
                      description:
                        type: string
                        description: 미션 설명
                        example: "특별한 할인 쿠폰을 획득하세요!"
        "400":
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: COMMON001
                  message:
                    type: string
                    example: 잘못된 요청입니다
        "500":
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: COMMON000
                  message:
                    type: string
                    example: 서버 에러, 관리자에게 문의 바랍니다.
