openapi: 3.0.0
info:
  title: Review API
  version: 1.0.0
  description: A simple Express Review API
servers:
  - url: http://localhost:3000/api
paths:
  /reviews/my:
    get:
      summary: 내가 작성한 리뷰
      description: Retrieve a paginated list of reviews written by the logged-in user.
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          required: true
          description: Page number, starts from 1
        - in: query
          name: pageSize
          schema:
            type: integer
            description: Number of items per page
      responses:
        '200':
          description: A list of reviews
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: The review ID
                    userId:
                      type: integer
                      description: The user ID of the reviewer
                    storeId:
                      type: integer
                      description: The store ID related to the review
                    rating:
                      type: integer
                      description: Rating given by the user
                    comment:
                      type: string
                      description: The review comment
        '500':
          description: Error message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
